name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install commitizen

      - name: Bump version and generate changelog
        id: bump_version
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md

      - name: Store version in env variable
        run: echo "VERSION=${{ steps.bump_version.outputs.version }}" >> $GITHUB_ENV

  build:
    needs: release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x86_64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executables
        run: |
          pyinstaller --onefile cli/main.py --name "codethreat-cli-${{ env.VERSION }}-${{ matrix.architecture }}-${{ matrix.os }}"
        shell: bash

      - name: Archive the build output for Windows
        if: startsWith(matrix.os, 'windows')
        run: |
          Compress-Archive -Path dist\*.exe -DestinationPath dist\codethreat-cli-${{ env.VERSION }}-${{ matrix.architecture }}-${{ matrix.os }}.zip
        shell: pwsh

      - name: Archive the build output for Linux and macOS
        if: matrix.os != 'windows-latest'
        run: |
          tar -czvf dist/codethreat-cli-${{ env.VERSION }}-${{ matrix.architecture }}-${{ matrix.os }}.tar.gz -C dist codethreat-cli-${{ env.VERSION }}-${{ matrix.architecture }}-${{ matrix.os }}
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: codethreat-cli-${{ env.VERSION }}-${{ matrix.architecture }}-${{ matrix.os }}
          path: dist/*

  release-artifacts:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: codethreat-cli-${{ env.VERSION }}-${{ matrix.architecture }}-${{ matrix.os }}

      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body_path: body.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/*
          asset_name: codethreat-cli-${{ env.VERSION }}-${{ matrix.architecture }}-${{ matrix.os }}.*
          asset_content_type: application/zip
